export const INITIAL_POSTS = [
    {
        id: 1,
        title: "React Hooks 완벽 가이드",
        excerpt: "React Hooks의 기본부터 고급 활용법까지 정리한 글입니다. useState, useEffect, useContext 등 주요 hooks들을 실제 예제와 함께 설명합니다.",
        content: "React Hooks는 함수형 컴포넌트에서 상태 관리와 생명주기 기능을 사용할 수 있게 해주는 강력한 기능입니다.\n\n주요 Hooks:\n- useState: 상태 관리\n- useEffect: 사이드 이펙트 처리\n- useContext: 전역 상태 관리\n- useCallback: 함수 메모이제이션\n- useMemo: 값 메모이제이션\n\n각 Hook의 사용법과 실전 예제를 통해 효과적인 React 개발 방법을 배워봅시다.",
        date: "2025-09-15",
        readTime: "8분",
        category: "Web Development",
        tags: ["React", "JavaScript", "Frontend"],
        likes: 42,
        comments: 7,
    },
    {
        id: 2,
        title: "2025년 웹 개발 트렌드",
        excerpt: "AI 기반 개발 도구의 발전, WebAssembly의 부상, 그리고 새로운 CSS 기능들까지. 2025년에 주목해야 할 주요 웹 기술 트렌드를 분석합니다.",
        content: "2025년 웹 개발 생태계는 급격한 변화를 겪고 있습니다.\n\n1. AI 코딩 어시스턴트의 일상화\n2. WebAssembly를 이용한 고성능 웹 앱\n3. CSS Nesting, Container Queries 등의 표준화\n4. Edge Computing의 확산\n\n이러한 트렌드가 프론트엔드 개발자에게 어떤 의미를 갖는지 심도 있게 다뤄봅니다.",
        date: "2025-08-20",
        readTime: "6분",
        category: "Web Development",
        tags: ["Trends", "WebAssembly", "AI"],
        likes: 35,
        comments: 12,
    },
    {
        id: 3,
        title: "알고리즘 문제 해결 전략",
        excerpt: "복잡한 알고리즘 문제를 만났을 때 어떻게 접근해야 할까요? 문제 분해부터 효율적인 코드 작성까지, 단계별 문제 해결 전략을 소개합니다.",
        content: "알고리즘 문제를 잘 풀기 위해서는 체계적인 접근이 필요합니다.\n\n1. 문제 이해하기: 입력과 출력, 제약조건 확인\n2. 예제 분석하기: 엣지 케이스 고려\n3. 알고리즘 설계하기: 시간복잡도 계산\n4. 코드 작성하기: 가독성 좋은 코드\n5. 디버깅 및 최적화\n\n실제 코딩 테스트 기출 문제를 통해 이 전략을 적용해봅니다.",
        date: "2025-07-10",
        readTime: "10분",
        category: "Algorithm",
        tags: ["Problem Solving", "Coding Test", "Python"],
        likes: 56,
        comments: 4,
    },
    {
        id: 4,
        title: "나의 개발 환경 셋업",
        excerpt: "생산성을 극대화하는 VS Code 설정, 터미널 커스터마이징, 그리고 유용한 익스텐션들을 공유합니다.",
        content: "개발 생산성은 도구의 활용도에 크게 좌우됩니다.\n\n- VS Code 테마 및 폰트 추천\n- 필수 익스텐션: ESLint, Prettier, GitLens\n- 터미널 설정: Oh My Zsh, Powerlevel10k\n- 생산성 팁: 단축키 활용, 스니펫 작성\n\n저만의 개발 환경 설정을 공개합니다.",
        date: "2025-06-05",
        readTime: "5분",
        category: "Personal",
        tags: ["Dev Environment", "VS Code", "Productivity"],
        likes: 28,
        comments: 9,
    },
];
